# Generated by Django 4.2.1 on 2023-09-03 13:50

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True, db_index=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField()),
                (
                    "discount",
                    models.IntegerField(
                        help_text="Percentage value (0 to 100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("active", models.BooleanField()),
            ],
            options={
                "ordering": ("-updated", "-created"),
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["-created"], name="coupons_cou_created_3362ee_idx"
                    )
                ],
            },
        ),
    ]
