# Generated by Django 4.2.1 on 2023-08-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_alter_category_name_alter_category_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
